apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          imagePullPolicy: Always
          image: miles0wu/simple-http-server:tracing
          ports:
            - containerPort: 80
      volumes:
      - name: service1-config
        configMap:
          name: service1-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service1-config
data:
  TRANSFER_ADDRESS: "http://service2"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
    - name: http-service1
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service1